-- 1. 성경통독 회차 정보 테이블
CREATE TABLE IF NOT EXISTS public.bible_readings (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    church_id text NOT NULL DEFAULT 'jesus-in',
    title text NOT NULL,
    audio_url text NOT NULL,
    description text,
    created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 2. 개인 통독 진행도 및 완료 상태 테이블
CREATE TABLE IF NOT EXISTS public.bible_reading_progress (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id uuid NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
    reading_id bigint NOT NULL REFERENCES public.bible_readings(id) ON DELETE CASCADE,
    church_id text NOT NULL DEFAULT 'jesus-in',
    is_completed boolean NOT NULL DEFAULT false,
    last_position integer NOT NULL DEFAULT 0, -- 초 단위 재생 위치 (이어듣기 지원용)
    completed_at timestamp with time zone,
    updated_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL,
    CONSTRAINT unique_user_reading UNIQUE (user_id, reading_id)
);

-- 3. 성경통독 댓글 테이블
CREATE TABLE IF NOT EXISTS public.bible_reading_comments (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    reading_id bigint NOT NULL REFERENCES public.bible_readings(id) ON DELETE CASCADE,
    user_id uuid NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
    user_name text NOT NULL,
    avatar_url text,
    content text NOT NULL,
    is_completed_comment boolean NOT NULL DEFAULT false, -- 댓글 작성 시 완료 인증 체크 여부
    created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 인덱스 추가 (조회 속도 최적화)
CREATE INDEX IF NOT EXISTS idx_bible_readings_church ON public.bible_readings(church_id);
CREATE INDEX IF NOT EXISTS idx_bible_reading_progress_user ON public.bible_reading_progress(user_id);
CREATE INDEX IF NOT EXISTS idx_bible_reading_comments_reading ON public.bible_reading_comments(reading_id);
